name=MiP Power Up: Pro Mini
version=0.0.3
author=Community
maintainer=Samuel Trassare <tiogaplanet@users.noreply.github.com>
sentence=An API to enable connecting the Arduino Pro Mini and clones to the WowWee MiP robot.
paragraph=Provides functionality to control the WowWee MiP robot using the MiP Power Up: Pro Mini.
category=Device Control
url=https://github.com/Tiogaplanet/MiP_Power_Up_Pro_Mini_lib
architectures=*
